on:
  schedule:
    - cron: '20 5,17 * * *'
  workflow_dispatch:

env:
  UPSTREAM_REMOTE: https://dawn.googlesource.com/dawn
  MOCK_UPSTREAM_REMOTE: https://github.com/eliemichel/Dawn-mock

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Merge from '${{ env.UPSTREAM_REMOTE }}'
        run: gh repo sync -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-build-artifacts:
    permissions:
      contents: write
    needs: sync-mirror
    uses: eliemichel/dawn-prebuilt/.github/workflows/build.yml@github
