on:
  schedule:
    - cron: '20 5,17 * * *'
  workflow_dispatch:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync with upstream mirror
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-build-artifacts:
    permissions:
      contents: write
    needs: sync-mirror
    uses: eliemichel/dawn-prebuilt/.github/workflows/build.yml@github
